name: npm publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      run: npm i
    - name: Testing
      run: node .github/test.js
    - name: Publishing
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        node .github/publish.js
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.npm_token }}